name: aahar_app
description: "An IOT and AI based Smart Farming System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.0
  flutter_slidable: ^3.1.2
  skeletonizer: ^1.4.2
  adaptive_theme: ^3.6.0
  google_nav_bar: ^5.0.7
  dashed_circular_progress_bar: ^0.0.6
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  # flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Aahar-white.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Aahar-transparent-md.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Aahar-black-md.png
    - assets/Aahar-t-black-transparent.png
    - assets/Aahar-black-transparent-md.png
    - assets/Aahar-black.png
    - assets/Aahar-t-transparent.png
    - assets/Aahar-transparent-md.png
    - assets/Aahar-transparent-sm.png
    - assets/Aahar-transparent.png
    - assets/Aahar-white.png